project:
  type: website
  output-dir: docs


website:
  sidebar:
    title: "風船ガムノート"
    style: "floating"
    search: true
    type: dark
    contents: auto
    tools:
    - icon: twitter
      href: https://twitter.com/Serika_Yuzuki
    - icon: github
      href: https://github.com/SerikaYuzuki
    collapse-level: 10
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  search: 
    location: sidebar
    type: textbox
  

format:
  html:
    mainfont: Hiragino
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    header-includes: |
      <link rel="stylesheet" media="screen" href="font/Hiragino.ttc" type="text/css"/>


