---
title: "無機化学"
---

# 原子軌道と周期律

## 原子の姿

- 原子という概念の成立

    - 原子は電子と陽子を含む小さな粒子

- 原子構造

    - 中心付近に正電荷が極端に集中した核が存在しており，Rutherfordのアルファ線散乱実験で観測された

- 水素原子の発光スペクトルの理解

すいそ原子の示す不連続な原子スペクトルの式は

$$\frac{1}{\lambda}=R\left(\frac{1}{n_1^2}-\frac{1}{n_2^2}\right)$$

これを説明しようとしたボーアモデルは

$$mrv=n\times \frac{h}{2\pi}$$

$$r=\frac{n^2\epsilon h^2}{\pi me^2}$$

$$E=\frac{1}{2}mv^2-\frac{e^2}{4\pi \epsilon r}=-\frac{me^4}{8\epsilon^2 h^2} \cdot \frac{1}{n^2}$$

これがかなりうまくいく．ってのはもう材料量子力学でやったよね．

## 電子軌道

De Broglieの物質波の概念

原子中の電子は，物質はが軌道に沿って一周し，位相が繋がって定在波ができる．

$$p = \frac{h}{\lambda}$$

$$\nabla^2 \Psi + \left( \frac{2\pi}{\lambda} \right)^2\Psi=0$$

エネルギー保存則

$$E=\frac{p^2}{2m}+V$$

これらを組み合わせればシュレディンガーの波動方程式になる．

$$\nabla^2 \Psi + \frac{8\pi m}{h^2}(E-V)\Psi=0$$

特に水素原子に対しては次のようになる

$$
\psi_{n l m}(r, \theta, \phi)= \sqrt{\left(\frac{2}{n a_0}\right)^3} \frac{(n-l-1) !}{2 n\{(n+l) !\}} e^{-r / n a_0}\left(\frac{2 r}{n a_0}\right)^l L_{n-l-1}^{2 l+1}\left(\frac{2 r}{n a_0}\right) \cdot Y_l^m(\theta, \phi)$$

$$ Y_l^m(\theta, \phi)=(-1)^{\frac{m+|m|}{2}} \sqrt{\frac{2 l+1}{4 \pi} \frac{(l-|m|) !}{(l+|m|) !} P_l^{m \mid}(\cos \theta) e^{i m \phi}}$$

$L,P$はランゲール陪関数とルジャンドル陪関数である．

ここで$l,m,n$３つの量子数が存在する事がシュレディンガー方程式が解を持つ条件となる．

|量子数名|特徴|要請|
|----|----|----|
|n|K,L,...の殻||
|l|s,p,...の軌道||
|m|||


# 化学結合の分類と結合

## 電子親和力

|組み合わせ|結合名|性質|
|----|----|----|
|陽性の強い，弱い元素|イオン結合|正負イオン間の静電引力による|
|陰性陽性の差が小さい元素同士|共有結合/金属結合|電子を出し合って安定化する．イオン化傾向が小さい元素同士だと金属結合になる|

## 共有結合

原子が２原子にまたがる新たな軌道に存在すると考えている．新たな結合には結合性軌道と反結合性軌道がある．これについては後ほど詳しく述べる．

- $\ce{H2O}$

|$\ce{H2O}$|$\ce{H2S}$|$\ce{H2Se}$|$\ce{H2Te}$|
|---|---|---|---|
|104.5|92|90|89|

- $\ce{NH3}$ 分子

|$\ce{NH3}$|$\ce{PH3}$|$\ce{AsH3}$|$\ce{SbH3}$|
|---|---|---|---|
|106.8|94|91.5|91.5|

- $\ce{C}$化合物

電子構造は次のとおり

$$\ce{(1s)^2(2s)^2(2p_x)^1(2p_y)^1}$$

これから混成軌道を作り上げる

$$\ce{(1s)^2(2s)^1(2p_x)^1(2p_y)^1(2p_z)^1}$$

$$\ce{Na^+_{gas}+Cl^-_{gas} -> NaCl +7.9eV}$$

## イオン結合

N個のMX結合

$$\Delta E = N \times \left( -\frac{(Ze)^2}{4\pi\epsilon_0R_0}+\frac{C}{R_0^m}\right)$$

上のものがイオン結晶を作る場合

$$\Delta E = N \times \left( -\alpha\frac{(Ze)^2}{4\pi\epsilon_0R_0}+\frac{C}{R_0^m}\right)$$

$\alpha $ はマーデルング定数で，その項はマーデルングポテンシャルと呼ばれる． $\Delta E$ は格子エネルギーである

### イオン性と電気陰性度(EN)

ポーリングの定義

イオン性は

$$\Delta(A-B)=D_{A-B}-\sqrt{D_{A-A}\times D_{B-B}}$$

ここで$D$は結合エネルギーのことである．また，電気陰性度は，

$$|\chi_A-\chi_B| \propto \sqrt{\Delta(A-B)}$$

Fに4を与えて，それ以外を比で求める．

### 双極子モーメント

$$\mu=\delta\times \gamma$$

HClのイオン制度は次のように定義される

$$\mu = 1.1 \text{D},\: \gamma = 1.27$$
$$1\text{D}=3.34\times 10^{-30}\text{Cm}$$

$$\frac{\mu}{\gamma \cdot 1.60 \times 10^{-19}}=\frac{1.1 \cdot 3.34\times 10^{-30}}{1.27\times 10^{-10} \cdot 1.60\times 10^{-19}}~0.18$$

これでイオン性が18%だとわかる．

剛体球モデルで，イオン半径は，様々な化合物中のイオン間距離を説明するように割り当てている．$R=R_-+r_+$で，$R$は実験地で求められるが，それ以降はわからない．なので人によって測定値が違う．


